### ISSUE TITLE
getting latest mm2 version fails

### ISSUE THREAD

**Issue by beanlover** [smk762/pytomicDEX_makerbot#3]
It seems the name of the zip file has "CI" instead of "Release" now.

If you update lib_helper.py and replace "Release" with "CI" (uppercase "i") then the download and extraction works.

My system is ubuntu desktop.

**Comment by smk762** [comment]
Thanks mate - Give it a shot now

**Comment by beanlover** [comment]
Works perfectly now...thanks!
